const PLAYER_SHAPES = {
    BALLISTIC: 1,
    EGG: 2,
}
const CONFIG = {
    PLAYER_WIDTH: 50,
    PLAYER_SHAPE: PLAYER_SHAPES.BALLISTIC,
    PLAYER_DEFAULT_HEIGHT: 300,
    PLAYER_JUMP_SPEED: 150,
    PLAYER_MAX_FLOAT_SPEED: 15,
    PLAYER_FLOAT_ACC: 0.50,

    PLATFORM_MIN_SPEED: 2,
    PLATFORM_MAX_SPEED: 10,
    PLATFORM_MIN_WIDTH: 50,
    PLATFORM_MAX_WIDTH: 280,
    PLATFORM_SHOWN_COUNT: 4,
    PLATFORM_ANIMATION_FRAME_COUNT: 30,

    PLATFORMS_LEVEL_HEIGHT: 100,
    // automatically calculated from screen.
    GAME_HEIGHT: 400,
    GAME_CONTAINER_ID: 'game-container',
    GAME_WIDTH: document.getElementById('game-container').offsetWidth,
    GAME_UPDATE_INTERVAL_MS: 20,
}